spring.application.name=jobportal
logging.pattern.console=${CONSOLE_LOG_PATTERN:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %cyan(%msg%n)}

spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:file:C:/Users/Moham/Documents;AUTO_SERVER=true
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
# SQL resources are moved to the root path of the JAR build files after built
# The classpath is a list of JAR files that the JVM searches through to find classes and resources at runtime.
#spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:sql/schema.sql
spring.sql.init.data-locations=classpath:sql/data.sql